export const BodyParts = [
  {
    id: 1,
    name: 'back',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/back2.jpg'),
  },
  {
    id: 2,
    name: 'cardio',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/Cardio.jpg'),
  },
  {
    id: 3,
    name: 'chest',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/chests.jpg'),
  },
  {
    id: 4,
    name: 'lower arms',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/LowerArm.jpg'),
  },
  {
    id: 5,
    name: 'lower legs',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/lower_legs2.jpg'),
  },
  {
    id: 6,
    name: 'neck',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/wide-neck.jpg'),
  },
  {
    id: 7,
    name: 'shoulders',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/shoulders.jpg'),
  },
  {
    id: 8,
    name: 'upper arms',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/uppper_fore_Arms.webp'),
  },
  {
    id: 9,
    name: 'upper legs',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/upper_legs.jpg'),
  },
  {
    id: 10,
    name: 'waist',
    selection: 'bodyPart',
    imagePath: require('../assets/images/bodyParts/waist2.jpg'),
  },
];

export const Equipments = [
  {
    id: 1,
    name: 'band',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Bands.jpg'),
  },
  {
    id: 2,
    name: 'barbell',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/barbell.jpg'),
  },
  {
    id: 3,
    name: 'body weight',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/body_weight.jpg'),
  },
  {
    id: 4,
    name: 'bosu ball',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Bosu_ball.jpg'),
  },
  {
    id: 5,
    name: 'rope',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Rope.jpg'),
  },
  {
    id: 6,
    name: 'ez barbell',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Olmpyic barbell.jpg'),
  },
  {
    id: 7,
    name: 'cable',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Cable.jpg'),
  },
  {
    id: 8,
    name: 'dumbbell',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/dumbells.jpg'),
  },
  {
    id: 9,
    name: 'hammer',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Hammer.jpg'),
  },
  {
    id: 10,
    name: 'trap bar',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/TrapBar.jpg'),
  },
  {
    id: 11,
    name: 'weighted',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/weightedvest.jpg'),
  },
  {
    id: 12,
    name: 'kettlebell',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/kettlebell.jpg'),
  },
  {
    id: 13,
    name: 'leverage machine',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/LeverageMachine.jpg'),
  },
  {
    id: 14,
    name: 'olympic barbell',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Olmpyic barbell.jpg'),
  },
  {
    id: 15,
    name: 'resistance band',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Bands.jpg'),
  },
  {
    id: 16,
    name: 'roller',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Rollers.jpeg'),
  },
  {
    id: 17,
    name: 'medicine ball',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/fitness_medicine_ball.jpg'),
  },
  {
    id: 18,
    name: 'sled machine',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/sledMachine.jpg'),
  },
  {
    id: 19,
    name: 'smith machine',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/smithMachine.jpg'),
  },
  {
    id: 20,
    name: 'elliptical machine',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Elliptical_Machine.jpg'),
  },
  {
    id: 21,
    name: 'stationary bike',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/stationaryBike.jpg'),
  },
  {
    id: 22,
    name: 'stepmill machine',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/stepMill.jpg'),
  },
  {
    id: 23,
    name: 'tire',
    selection: 'equipment',
    imagePath: require('../assets/images/Equipments/Tire.jpg'),
  },
];

export const restaurants = [
  {
    id: '1',
    name: 'Requiem of Pasta',
    category: 'Italian Dance',
    rating: 2,
    location: '123 Main St, Los Angeles, CA',
    phone: '(123) 456-7890',
    price: '$$$',
    image_url: 'https://picsum.photos/seed/1/200/300?food',
    opening_hours: '10:00 AM - 10:00 PM',
    reviews: [
      {
        review_id: 101,
        user_id: 9,
        rating: 6,
        text: "Amazing pasta, the best I've ever had!",
        date: '2024-09-23',
      },
      {
        review_id: 102,
        user_id: 2,
        rating: 4,
        text: 'Great ambiance but the service was a bit slow.',
        date: '2024-09-22',
      },
    ],
  },
  {
    id: '2',
    name: 'Pasta Palace',
    category: 'Italian',
    rating: 4.5,
    location: '456 Main St, Los Angeles, CA',
    phone: '(123) 456-7890',
    price: '$$',
    image_url: 'https://picsum.photos/seed/2/200/300?food',
    opening_hours: '9:00 AM - 9:00 PM',
    reviews: [
      {
        review_id: 103,
        user_id: 1,
        rating: 5,
        text: "Amazing pasta, the best I've ever had!",
        date: '2024-09-23',
      },
    ],
  },
  {
    id: '3',
    name: 'Burger Barn',
    category: 'American',
    rating: 4,
    location: '789 Oak St, San Francisco, CA',
    phone: '(987) 654-3210',
    price: '$',
    image_url: 'https://picsum.photos/seed/3/200/300?food',
    opening_hours: '11:00 AM - 11:00 PM',
    reviews: [
      {
        review_id: 104,
        user_id: 3,
        rating: 4,
        text: 'Solid burgers, good price!',
        date: '2024-09-21',
      },
    ],
  },
  {
    id: '4',
    name: 'Pizza Paradise',
    category: 'Italian',
    rating: 4.2,
    location: '321 Elm St, New York, NY',
    phone: '(234) 567-8910',
    price: '$$',
    image_url: 'https://picsum.photos/seed/4/200/300?food',
    opening_hours: '10:00 AM - 11:00 PM',
    reviews: [
      {
        review_id: 105,
        user_id: 4,
        rating: 4,
        text: 'The pizza was great, loved the crust!',
        date: '2024-09-20',
      },
    ],
  },
  {
    id: '5',
    name: 'Taco Tower',
    category: 'Mexican',
    rating: 3.8,
    location: '1234 Pine St, Austin, TX',
    phone: '(345) 678-9101',
    price: '$',
    image_url: 'https://picsum.photos/seed/5/200/300?food',
    opening_hours: '8:00 AM - 8:00 PM',
    reviews: [
      {
        review_id: 106,
        user_id: 5,
        rating: 3,
        text: 'Tacos were okay, but the portions were small.',
        date: '2024-09-19',
      },
    ],
  },
  {
    id: '6',
    name: 'Sushi Spot',
    category: 'Japanese',
    rating: 4.7,
    location: '789 River St, Seattle, WA',
    phone: '(456) 789-0123',
    price: '$$$$',
    image_url: 'https://picsum.photos/seed/6/200/300?food',
    opening_hours: '11:00 AM - 10:00 PM',
    reviews: [],
  },
  {
    id: '7',
    name: 'BBQ Bliss',
    category: 'American',
    rating: 4.6,
    location: '123 Lake St, Dallas, TX',
    phone: '(567) 890-1234',
    price: '$$$',
    image_url: 'https://picsum.photos/seed/7/200/300?food',
    opening_hours: '12:00 PM - 11:00 PM',
    reviews: [],
  },
  {
    id: '8',
    name: 'Dim Sum Delight',
    category: 'Chinese',
    rating: 4.3,
    location: '456 Forest St, San Diego, CA',
    phone: '(678) 901-2345',
    price: '$$',
    image_url: 'https://picsum.photos/seed/8/200/300?food',
    opening_hours: '10:00 AM - 9:00 PM',
    reviews: [],
  },
  {
    id: '9',
    name: 'The Curry Corner',
    category: 'Indian',
    rating: 4.8,
    location: '789 Bridge St, Boston, MA',
    phone: '(789) 012-3456',
    price: '$$$',
    image_url: 'https://picsum.photos/seed/9/200/300?food',
    opening_hours: '12:00 PM - 10:00 PM',
    reviews: [],
  },
  {
    id: '10',
    name: 'Pho Paradise',
    category: 'Vietnamese',
    rating: 4.9,
    location: '321 Beach St, Miami, FL',
    phone: '(890) 123-4567',
    price: '$$',
    image_url: 'https://picsum.photos/seed/10/200/300?food',
    opening_hours: '9:00 AM - 8:00 PM',
    reviews: [],
  },
  {
    id: '11',
    name: 'Crepes & Cones',
    category: 'French',
    rating: 4.1,
    location: '100 Baker St, San Diego, CA',
    phone: '(901) 234-5678',
    price: '$$$',
    image_url: 'https://picsum.photos/seed/11/200/300?food',
    opening_hours: '8:00 AM - 9:00 PM',
    reviews: [],
  },
  {
    id: '12',
    name: 'Tempura Temple',
    category: 'Japanese',
    rating: 4.5,
    location: '345 Sushi St, Seattle, WA',
    phone: '(123) 654-9876',
    price: '$$$$',
    image_url: 'https://picsum.photos/seed/12/200/300?food',
    opening_hours: '11:00 AM - 9:00 PM',
    reviews: [],
  },
  {
    id: '13',
    name: 'The Spicy Shack',
    category: 'Mexican',
    rating: 4.3,
    location: '234 Salsa Ln, Austin, TX',
    phone: '(432) 345-6789',
    price: '$',
    image_url: 'https://picsum.photos/seed/13/200/300?food',
    opening_hours: '7:00 AM - 8:00 PM',
    reviews: [],
  },
  {
    id: '14',
    name: 'Gourmet Grills',
    category: 'American',
    rating: 4.8,
    location: '456 BBQ St, Chicago, IL',
    phone: '(456) 789-0123',
    price: '$$$$',
    image_url: 'https://picsum.photos/seed/14/200/300?food',
    opening_hours: '12:00 PM - 11:00 PM',
    reviews: [],
  },
  {
    id: '15',
    name: 'Curry Quest',
    category: 'Indian',
    rating: 4.7,
    location: '123 Spice St, Boston, MA',
    phone: '(789) 012-3456',
    price: '$$$',
    image_url: 'https://picsum.photos/seed/15/200/300?food',
    opening_hours: '11:00 AM - 10:00 PM',
    reviews: [],
  },
  {
    id: '16',
    name: 'Deli Delight',
    category: 'American',
    rating: 4.1,
    location: '789 Bagel Blvd, New York, NY',
    phone: '(890) 123-4567',
    price: '$',
    image_url: 'https://picsum.photos/seed/16/200/300?food',
    opening_hours: '6:00 AM - 6:00 PM',
    reviews: [],
  },
  {
    id: '17',
    name: 'Fusion Feast',
    category: 'Fusion',
    rating: 4.9,
    location: '123 Flavor St, Miami, FL',
    phone: '(123) 654-9876',
    price: '$$$$',
    image_url: 'https://picsum.photos/seed/17/200/300?food',
    opening_hours: '5:00 PM - 12:00 AM',
    reviews: [],
  },
  {
    id: '18',
    name: 'Vegan Vibes',
    category: 'Vegan',
    rating: 4.2,
    location: '234 Herb Ln, Portland, OR',
    phone: '(432) 345-6789',
    price: '$$',
    image_url: 'https://picsum.photos/seed/18/200/300?food',
    opening_hours: '9:00 AM - 9:00 PM',
    reviews: [],
  },
  {
    id: '19',
    name: 'Paella Palace',
    category: 'Spanish',
    rating: 4.6,
    location: '456 Valencia St, Los Angeles, CA',
    phone: '(456) 789-0123',
    price: '$$$$',
    image_url: 'https://picsum.photos/seed/19/200/300?food',
    opening_hours: '11:00 AM - 11:00 PM',
    reviews: [],
  },
  {
    id: '20',
    name: 'Tapas Town',
    category: 'Spanish',
    rating: 4.8,
    location: '789 Tapas St, San Francisco, CA',
    phone: '(789) 012-3456',
    price: '$$$',
    image_url: 'https://picsum.photos/seed/20/200/300?food',
    opening_hours: '12:00 PM - 10:00 PM',
    reviews: [],
  },
];

export const ExcerciseDB_API_KEY =
  'efbbf9641cmsh31c8cee6dcedda0p1ff29fjsn1e1c07bad08d';
